# Generated by Django 5.2.14 on 2026-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_workspace_current_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ayrshare_profile_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ayrshare Profile Key'),
        ),
    ]
