# Generated by Django 5.2.17 on 2026-08-16 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Name')),
                ('max_video_duration_seconds', models.IntegerField(default=60, verbose_name='Max Duration (sec)')),
                ('max_resolution', models.CharField(choices=[('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10, verbose_name='Max Resolution')),
                ('has_watermark', models.BooleanField(default=True, verbose_name='Has Watermark')),
                ('allow_scheduling', models.BooleanField(default=False, verbose_name='Allow Scheduling')),
                ('allow_crossposting', models.BooleanField(default=False, verbose_name='Allow Crossposting')),
                ('has_seo_optimization', models.BooleanField(default=False, verbose_name='Has SEO Optimization')),
                ('has_thumbnail_engine', models.BooleanField(default=False, verbose_name='Has Thumbnail Engine')),
                ('base_discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 0.20 for 20% discount', max_digits=5, verbose_name='Base Discount Rate')),
                ('max_members', models.IntegerField(default=1, verbose_name='Max Members')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('SPEND', 'Gasto'), ('REFUND', 'Reembolso')], default='SPEND', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='Available Balance')),
                ('reserved_balance', models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='Reserved Balance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
