# Generated by Django 5.2.17 on 2026-08-16 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('s3_object_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='R2/S3 Key')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('virality_score', models.IntegerField(default=0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('rendering', 'Renderizando'), ('completed', 'Listo para descargar'), ('published', 'Publicado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('primary_font', models.FileField(blank=True, null=True, upload_to='assets/fonts/')),
                ('secondary_font', models.FileField(blank=True, null=True, upload_to='assets/fonts/')),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', max_length=7)),
                ('accent_color', models.CharField(default='#FFFF00', max_length=7)),
                ('watermark_logo', models.ImageField(blank=True, null=True, upload_to='assets/logos/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='assets/videos/')),
                ('outro_video', models.FileField(blank=True, null=True, upload_to='assets/videos/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_kits', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kits', to='users.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ClipLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('layer_type', models.CharField(choices=[('text', 'Texto / SubtÃ\xadtulo'), ('image', 'Imagen / Logo'), ('video', 'Video Overlay'), ('audio', 'Audio / MÃºsica')], max_length=20)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('asset_file', models.FileField(blank=True, null=True, upload_to='assets/layers/')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('prompt_used', models.CharField(blank=True, max_length=255)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='videos.videoclip')),
            ],
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nuevo Proyecto', max_length=255)),
                ('original_r2_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Original R2 Key')),
                ('proxy_r2_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Proxy R2 Key')),
                ('final_export_r2_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Final Export R2 Key')),
                ('project_type', models.CharField(choices=[('repurpose', 'Viralizar (Largo -> Cortos)'), ('single_edit', 'EdiciÃ³n (Clip -> Clip)')], default='repurpose', max_length=20)),
                ('editing_style', models.CharField(choices=[('dynamic', 'DinÃ¡mico / Gaming'), ('minimalist', 'Minimalista / Podcast'), ('vlog', 'Vlog / Lifestyle'), ('hormozi', 'Estilo Hormozi'), ('custom', 'Personalizado')], default='dynamic', max_length=20)),
                ('intelligence_level', models.CharField(choices=[('fast', 'RÃ¡pido (GPT-4o-mini)'), ('smart', 'Inteligente (GPT-4o)')], default='fast', max_length=10)),
                ('auto_render_bypass', models.BooleanField(default=False, help_text='Si es True, salta el paso de aprobaciÃ³n y renderiza directo.')),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Vertical (TikTok/Reels)'), ('1:Post', 'Cuadrado (Post)'), ('16:9', 'Horizontal (YouTube)')], default='9:16', max_length=10)),
                ('render_layout', models.CharField(choices=[('fill', 'Relleno (Crop Central)'), ('fit', 'Ajustar (Bordes Negros)'), ('blurred', 'Fondo Borroso'), ('split', 'Split Screen (Gaming)'), ('pip', 'Picture in Picture'), ('versus', 'Versus (2 Personas)'), ('active', 'Speaker DinÃ¡mico')], default='fill', max_length=10)),
                ('gameplay_position', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10)),
                ('camera_selection_position', models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10)),
                ('manual_camera_x', models.FloatField(default=0.5)),
                ('manual_camera_y', models.FloatField(default=0.2)),
                ('manual_camera_zoom', models.FloatField(default=1.0)),
                ('speaker_tracking', models.BooleanField(default=False)),
                ('add_subtitles', models.BooleanField(default=True, help_text='Â¿Deseas agregar subtÃ\xadtulos automÃ¡ticos?')),
                ('subtitle_color', models.CharField(default='#FFFF00', help_text='Color hexadecimal', max_length=7)),
                ('subtitle_with_emojis', models.BooleanField(default=False, help_text='Â¿Agregar emojis automÃ¡ticos?')),
                ('subtitle_words_per_segment', models.IntegerField(default=3, help_text='MÃ¡ximo de palabras')),
                ('subtitle_size', models.CharField(choices=[('small', 'PequeÃ±o'), ('medium', 'Mediano'), ('large', 'Grande')], default='medium', max_length=10)),
                ('subtitle_position', models.CharField(choices=[('top', 'Arriba'), ('center', 'Centro'), ('bottom', 'Abajo')], default='bottom', max_length=10)),
                ('use_facetracking', models.BooleanField(default=False, help_text='Â¿Deseas que la cÃ¡mara siga automÃ¡ticamente el rostro?')),
                ('remove_silences', models.BooleanField(default=False, help_text='¿Deseas eliminar los silencios automáticamente para hacer el video más dinámico?')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='videos/raw/%Y/%m/')),
                ('video_url', models.URLField(blank=True, help_text='URL de YouTube/Vimeo si no se sube archivo', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ai_rationale_log', models.JSONField(blank=True, default=dict, verbose_name='AI Rationale')),
                ('transcript_data', models.JSONField(blank=True, null=True, verbose_name='Transcript Data (JSON)')),
                ('approved_segments', models.JSONField(blank=True, null=True, verbose_name='Approved Segments (Floats)')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('ingesting', 'Ingesta / Analizando IA'), ('awaiting_approval', 'Esperando AprobaciÃ³n'), ('rendering', 'Renderizando'), ('completed', 'Completado'), ('failed', 'Error')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.brandkit')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='videoclip',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='videos.videoproject'),
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM_REELS', 'Instagram Reels'), ('YOUTUBE_SHORTS', 'YouTube Shorts')], max_length=20)),
                ('publish_at', models.DateTimeField(verbose_name='Publish Date (UTC)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programado'), ('QUEUED', 'En Cola (ETA)'), ('PROCESSING', 'Publicando...'), ('PUBLISHED', 'Publicado'), ('FAILED', 'Fallido')], default='DRAFT', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('generated_caption', models.TextField(blank=True, null=True, verbose_name='AI Caption')),
                ('generated_hashtags', models.JSONField(blank=True, null=True, verbose_name='AI Hashtags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='videos.videoclip')),
            ],
            options={
                'ordering': ['publish_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='videos_sche_status_96eb1a_idx')],
            },
        ),
    ]
