# Generated by Django 5.2.18 on 2026-10-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='pipeline_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='pipeline_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='pipeline_error_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='pipeline_stage',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('audio_extracted', 'Fuente preparada'), ('transcribed', 'Transcrito'), ('clips_selected', 'Clips seleccionados'), ('render_dispatched', 'Render despachado'), ('completed', 'Completado'), ('partial', 'Completado con errores'), ('failed', 'Error')], default='uploaded', max_length=32),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='pipeline_stage_status',
            field=models.JSONField(blank=True, default=dict, help_text='Per-stage pending/running/completed/failed.'),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('rendering', 'Renderizando'), ('completed', 'Listo para descargar'), ('published', 'Publicado'), ('failed', 'Error')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('ingesting', 'Ingesta / Analizando IA'), ('awaiting_approval', 'Esperando AprobaciÃ³n'), ('rendering', 'Renderizando'), ('completed', 'Completado'), ('partial', 'Completado con errores'), ('failed', 'Error')], default='uploaded', max_length=20),
        ),
    ]
