# Generated by Django 5.2.18 on 2026-10-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_pipeline_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('transcription', 'Transcription'), ('selection', 'Selection')], max_length=16)),
                ('pipeline_version', models.CharField(choices=[('legacy', 'Legacy'), ('v2', 'AI Core V2')], max_length=8)),
                ('attempt', models.PositiveSmallIntegerField(help_text='VideoProject.pipeline_attempts when recorded.')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('fallback', 'Fallback')], max_length=8)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('resolved_model', models.CharField(blank=True, max_length=64, null=True)),
                ('success', models.BooleanField()),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('audio_seconds', models.FloatField(blank=True, null=True)),
                ('latency_seconds', models.FloatField()),
                ('cached', models.BooleanField(default=False)),
                ('estimated_cost_usd', models.DecimalField(blank=True, decimal_places=9, max_digits=14, null=True)),
                ('pricing_version', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='videos.videoproject')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'project'], name='ai_usage_created_project_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'stage', 'attempt', 'role'), name='uniq_ai_usage_project_stage_attempt_role')],
            },
        ),
    ]
