# Generated by Django 6.0.4 on 2026-05-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_brandkit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='gameplay_position',
            field=models.CharField(choices=[('left', 'Izquierda'), ('center', 'Centro'), ('right', 'Derecha')], default='center', max_length=10),
        ),
    ]
