# Generated by Django 6.0.4 on 2026-05-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_videoproject_gameplay_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='speaker_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='render_layout',
            field=models.CharField(choices=[('fill', 'Relleno (Crop Central)'), ('fit', 'Ajustar (Bordes Negros)'), ('blurred', 'Fondo Borroso'), ('split', 'Split Screen (Gaming)'), ('pip', 'Picture in Picture'), ('versus', 'Versus (2 Personas)'), ('active', 'Speaker Dinámico')], default='fill', max_length=10),
        ),
    ]
