# Generated by Django 5.2.14 on 2026-05-16 23:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoproject_speaker_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM_REELS', 'Instagram Reels'), ('YOUTUBE_SHORTS', 'YouTube Shorts')], max_length=20)),
                ('publish_at', models.DateTimeField(verbose_name='Publish Date (UTC)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programado'), ('QUEUED', 'En Cola (ETA)'), ('PROCESSING', 'Publicando...'), ('PUBLISHED', 'Publicado'), ('FAILED', 'Fallido')], default='DRAFT', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='videos.videoclip')),
            ],
            options={
                'ordering': ['publish_at'],
                'indexes': [models.Index(fields=['status', 'publish_at'], name='videos_sche_status_96eb1a_idx')],
            },
        ),
    ]
