# Generated by Django 5.2.14 on 2026-05-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_scheduledpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoclip',
            name='output_file',
        ),
        migrations.AddField(
            model_name='videoclip',
            name='s3_object_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='S3 Key'),
        ),
    ]
