# Generated by Django 5.2.14 on 2026-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_videoclip_output_file_videoclip_s3_object_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='generated_caption',
            field=models.TextField(blank=True, null=True, verbose_name='AI Caption'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='generated_hashtags',
            field=models.JSONField(blank=True, null=True, verbose_name='AI Hashtags'),
        ),
    ]
