# Generated by Django 5.2.14 on 2026-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_scheduledpost_generated_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoproject',
            name='ai_rationale_log',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI Rationale'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='auto_render_bypass',
            field=models.BooleanField(default=False, help_text='Si es True, salta el paso de aprobación y renderiza directo.'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='original_s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Original S3 Key'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='proxy_s3_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Proxy S3 Key'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Subido'), ('ingesting', 'Ingesta / Analizando IA'), ('awaiting_approval', 'Esperando Aprobación'), ('rendering', 'Renderizando'), ('completed', 'Completado'), ('failed', 'Error')], default='uploaded', max_length=20),
        ),
    ]
