# Generated by Django 5.2.14 on 2026-05-18 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_videoproject_ai_rationale_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandkit',
            name='ai_instructions',
        ),
        migrations.RemoveField(
            model_name='brandkit',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='brandkit',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='cliplayer',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='cliplayer',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cliplayer',
            name='position_data',
        ),
        migrations.RemoveField(
            model_name='cliplayer',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='ai_metadata',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='original_s3_key',
        ),
        migrations.RemoveField(
            model_name='videoproject',
            name='proxy_s3_key',
        ),
        migrations.AddField(
            model_name='brandkit',
            name='accent_color',
            field=models.CharField(default='#FFFF00', max_length=7),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='primary_font',
            field=models.FileField(blank=True, null=True, upload_to='assets/fonts/'),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='secondary_font',
            field=models.FileField(blank=True, null=True, upload_to='assets/fonts/'),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_kits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandkit',
            name='watermark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/logos/'),
        ),
        migrations.AddField(
            model_name='cliplayer',
            name='asset_file',
            field=models.FileField(blank=True, null=True, upload_to='assets/layers/'),
        ),
        migrations.AddField(
            model_name='cliplayer',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cliplayer',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliplayer',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='approved_segments',
            field=models.JSONField(blank=True, null=True, verbose_name='Approved Segments (Floats)'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='final_export_r2_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Final Export R2 Key'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='original_r2_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Original R2 Key'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='proxy_r2_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Proxy R2 Key'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='transcript_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Transcript Data (JSON)'),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='assets/videos/'),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='outro_video',
            field=models.FileField(blank=True, null=True, upload_to='assets/videos/'),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='primary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='brandkit',
            name='secondary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='cliplayer',
            name='layer_type',
            field=models.CharField(choices=[('text', 'Texto / Subtítulo'), ('image', 'Imagen / Logo'), ('video', 'Video Overlay'), ('audio', 'Audio / Música')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cliplayer',
            name='start_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='s3_object_key',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='R2/S3 Key'),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='aspect_ratio',
            field=models.CharField(choices=[('9:16', 'Vertical (TikTok/Reels)'), ('1:Post', 'Cuadrado (Post)'), ('16:9', 'Horizontal (YouTube)')], default='9:16', max_length=10),
        ),
    ]
