# Generated by Django 5.2.14 on 2026-05-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_remove_brandkit_ai_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandkit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
